####################
# set up languages
language: c

####################
# install packages
before_install:
  - travis/install-deps.sh

####################
# build script
script:
  - export PATH=.:${PATH} && ./travis/autogen.sh && ./travis/configure.sh && make && make install && make check && ./travis/distcheck.sh

####################
# branch configuration
branches:
  only:
  - master

####################
# os environments
sudo: required
osx_image: xcode7.3

####################
# deploy
after_success:
  - ./travis/deploy.sh
####################
# build matrix
matrix:
  include:
  - { os: linux, dist: precise }
  - { os: linux, dist: trusty }
  - { os: osx }
  allow_failures:
    - os: osx

####################
# token for uploading releases
env:
  global:
    secure: jP31yv0GqNtqsQ+9pse38sIIGe+EAkyrkBYPURBUC0YUwvNztS+OBATk45fIfmDbChLizYXnShSUBbLHQ9KluQvNlvZ6Wvx2wgZ3eBuYaMrIaDPuhTc1BIlJdxo5CLNwyzVfhW5QiwJafkmZTuVzCr4J77VqVHoxwN5+Vn8FT7AxE3G7ONyiSKVdPHi4H2n+DKnJvx9j/tkS9Ne0eHsFGMwxgWZg5mZpOQ4VnUErXxFluLpBP6v0Bg2rHajpQThTYoA8ezW97lzt1Ivy8eCLAApu5+jimfGjcQO8B3rd5d0ugTl/p5X3T1LjTPsOGcwgzDmnXJ7iPbVsRVL7oXuUDYqOSvmKUb8CL+5rBi8OAG9vHKW3X6MsBDL233oCya05Rcwq/l8Gonoda7Mvc3DTk/dhKJDSyaG9dBx695ohJiYGnVJ2ZhNjFOEuwCi+oKx9EHtOIYkt7tLRZ194/lKVYXnSUsquPSK5wIp4dy8HfiY4c6FLW7qI+ZSrDYXgUDFXEChEC+f4Je5QB9lUOgPAxadc1Dcto8vue/EEFW/KcfBZQg/zLyYeF7tHDMiaxXy+s0gql9YDzw6kffR8M2d0D6kcjxgO3mn2aaow8lD9+vJ39NAfC9sluYleyN5pdmdfRBs7vCaCj9Vlmy2BpFQt+8KgVc7VdN8HEbIGiZ4+08A=
